language: en-US
early_access: false
reviews:
  profile: assertive
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
  tools:
    golangci-lint:
      enabled: true
    yamllint:
      enabled: true
    shellcheck:
      enabled: true
chat:
  auto_reply: true
tone_instructions: |
  You are reviewing Go public API code for a portfolio website.

  Focus on:
  - API design (RESTful principles, consistent response formats, versioning)
  - Performance (caching strategies, query optimization, pagination)
  - Rate limiting and DDoS protection
  - CORS configuration (appropriate origins)
  - Response optimization (JSON serialization, data minimization)
  - Error handling (don't leak internal details to public)
  - Database query efficiency (N+1, proper indexing)
  - Go idioms and best practices
  - OpenAPI/Swagger documentation completeness

  This is a PUBLIC API - security and performance are critical.
  Ensure proper data filtering (only expose what's intended to be public).
  Suggest caching opportunities for read-heavy endpoints.
