// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/certifications": {
            "get": {
                "description": "Get list of all certifications",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "certifications"
                ],
                "summary": "Get all certifications",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_GunarsK-portfolio_public-api_internal_models.Certification"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/experience": {
            "get": {
                "description": "Get list of all work experience entries",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "experience"
                ],
                "summary": "Get all work experience",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_GunarsK-portfolio_public-api_internal_models.WorkExperience"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if service is healthy",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/miniatures": {
            "get": {
                "description": "Get list of all miniature painting projects with images",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "miniatures"
                ],
                "summary": "Get all miniature projects",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_GunarsK-portfolio_public-api_internal_models.MiniatureProject"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/miniatures/themes": {
            "get": {
                "description": "Get list of all miniature themes with their associated projects",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "miniatures"
                ],
                "summary": "Get all miniature themes with projects",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_GunarsK-portfolio_public-api_internal_models.MiniatureTheme"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/miniatures/{id}": {
            "get": {
                "description": "Get detailed information about a specific miniature project",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "miniatures"
                ],
                "summary": "Get miniature project by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Miniature Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_GunarsK-portfolio_public-api_internal_models.MiniatureProject"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "description": "Get the portfolio owner's profile information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Get profile information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_GunarsK-portfolio_public-api_internal_models.Profile"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/projects": {
            "get": {
                "description": "Get list of all portfolio projects with technologies",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Get all portfolio projects",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_GunarsK-portfolio_public-api_internal_models.PortfolioProject"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/projects/{id}": {
            "get": {
                "description": "Get detailed information about a specific portfolio project",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Get portfolio project by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_GunarsK-portfolio_public-api_internal_models.PortfolioProject"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/skills": {
            "get": {
                "description": "Get list of all visible skills organized by category",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "skills"
                ],
                "summary": "Get all skills",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_GunarsK-portfolio_public-api_internal_models.Skill"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_GunarsK-portfolio_portfolio-common_models.Image": {
            "type": "object",
            "properties": {
                "caption": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "github_com_GunarsK-portfolio_portfolio-common_models.MiniaturePaint": {
            "type": "object",
            "required": [
                "manufacturer",
                "name"
            ],
            "properties": {
                "colorHex": {
                    "description": "ColorHex is the hexadecimal color code in #RRGGBB or #RGB format (e.g., #FF5733, #F00)",
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "manufacturer": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "paintType": {
                    "description": "PaintType categorizes the paint (Base, Layer, Shade, Wash, Contrast, Dry, Technical, Metallic, Air, Primer, Edge, Glaze, Ink)\nDatabase enforces these values via CHECK constraint",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_GunarsK-portfolio_portfolio-common_models.MiniatureProject": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "completedDate": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "difficulty": {
                    "type": "string"
                },
                "displayOrder": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_GunarsK-portfolio_portfolio-common_models.Image"
                    }
                },
                "manufacturer": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "paints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_GunarsK-portfolio_portfolio-common_models.MiniaturePaint"
                    }
                },
                "scale": {
                    "type": "string"
                },
                "techniques": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "theme": {
                    "description": "Associations",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_GunarsK-portfolio_portfolio-common_models.MiniatureTheme"
                        }
                    ]
                },
                "themeId": {
                    "type": "integer"
                },
                "timeSpent": {
                    "type": "number"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_GunarsK-portfolio_portfolio-common_models.MiniatureTheme": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "coverImageFile": {
                    "description": "Associations",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_GunarsK-portfolio_portfolio-common_models.StorageFile"
                        }
                    ]
                },
                "coverImageId": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "displayOrder": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "miniatures": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_GunarsK-portfolio_portfolio-common_models.MiniatureProject"
                    }
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_GunarsK-portfolio_portfolio-common_models.Skill": {
            "type": "object",
            "required": [
                "skill",
                "skillTypeId"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "displayOrder": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "isVisible": {
                    "type": "boolean"
                },
                "skill": {
                    "type": "string"
                },
                "skillType": {
                    "$ref": "#/definitions/github_com_GunarsK-portfolio_portfolio-common_models.SkillType"
                },
                "skillTypeId": {
                    "type": "integer"
                },
                "type": {
                    "description": "Computed field",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_GunarsK-portfolio_portfolio-common_models.SkillType": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "displayOrder": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_GunarsK-portfolio_portfolio-common_models.StorageFile": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "fileName": {
                    "type": "string"
                },
                "fileSize": {
                    "type": "integer"
                },
                "fileType": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "mimeType": {
                    "type": "string"
                },
                "url": {
                    "description": "Computed field",
                    "type": "string"
                }
            }
        },
        "github_com_GunarsK-portfolio_public-api_internal_models.Certification": {
            "type": "object",
            "required": [
                "issueDate",
                "issuer",
                "name"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "credentialId": {
                    "type": "string"
                },
                "credentialUrl": {
                    "type": "string"
                },
                "expiryDate": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "issueDate": {
                    "type": "string"
                },
                "issuer": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_GunarsK-portfolio_public-api_internal_models.MiniatureProject": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "completedDate": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "difficulty": {
                    "type": "string"
                },
                "displayOrder": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_GunarsK-portfolio_portfolio-common_models.Image"
                    }
                },
                "manufacturer": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "paints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_GunarsK-portfolio_portfolio-common_models.MiniaturePaint"
                    }
                },
                "scale": {
                    "type": "string"
                },
                "techniques": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "theme": {
                    "description": "Associations",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_GunarsK-portfolio_portfolio-common_models.MiniatureTheme"
                        }
                    ]
                },
                "themeId": {
                    "type": "integer"
                },
                "timeSpent": {
                    "type": "number"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_GunarsK-portfolio_public-api_internal_models.MiniatureTheme": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "coverImageFile": {
                    "description": "Associations",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_GunarsK-portfolio_portfolio-common_models.StorageFile"
                        }
                    ]
                },
                "coverImageId": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "displayOrder": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "miniatures": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_GunarsK-portfolio_portfolio-common_models.MiniatureProject"
                    }
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_GunarsK-portfolio_public-api_internal_models.PortfolioProject": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "category": {
                    "type": "string"
                },
                "challenges": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "displayOrder": {
                    "type": "integer"
                },
                "endDate": {
                    "type": "string"
                },
                "featured": {
                    "type": "boolean"
                },
                "features": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "githubUrl": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "imageFile": {
                    "description": "Associations",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_GunarsK-portfolio_portfolio-common_models.StorageFile"
                        }
                    ]
                },
                "imageFileId": {
                    "type": "integer"
                },
                "isOngoing": {
                    "type": "boolean"
                },
                "learnings": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "liveUrl": {
                    "type": "string"
                },
                "longDescription": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "startDate": {
                    "type": "string"
                },
                "teamSize": {
                    "type": "integer"
                },
                "technologies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_GunarsK-portfolio_portfolio-common_models.Skill"
                    }
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_GunarsK-portfolio_public-api_internal_models.Profile": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "avatarFile": {
                    "description": "Now exposed to JSON",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_GunarsK-portfolio_portfolio-common_models.StorageFile"
                        }
                    ]
                },
                "avatarFileId": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "resumeFile": {
                    "description": "Now exposed to JSON",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_GunarsK-portfolio_portfolio-common_models.StorageFile"
                        }
                    ]
                },
                "resumeFileId": {
                    "type": "integer"
                },
                "tagline": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_GunarsK-portfolio_public-api_internal_models.Skill": {
            "type": "object",
            "required": [
                "skill",
                "skillTypeId"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "displayOrder": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "isVisible": {
                    "type": "boolean"
                },
                "skill": {
                    "type": "string"
                },
                "skillType": {
                    "$ref": "#/definitions/github_com_GunarsK-portfolio_portfolio-common_models.SkillType"
                },
                "skillTypeId": {
                    "type": "integer"
                },
                "type": {
                    "description": "Computed field",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_GunarsK-portfolio_public-api_internal_models.WorkExperience": {
            "type": "object",
            "required": [
                "company",
                "position",
                "startDate"
            ],
            "properties": {
                "company": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "endDate": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isCurrent": {
                    "type": "boolean"
                },
                "position": {
                    "type": "string"
                },
                "startDate": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Portfolio Public API",
	Description:      "Public read-only API for portfolio data",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
